# Generated by Django 3.2 on 2022-10-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField()),
                ('duration_in_days', models.SmallIntegerField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked-in', 'Checked-in'), ('checked-out', 'Checked-out'), ('canceled', 'Canceled'), ('abandoned', 'Abandoned')], max_length=50)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('style', models.CharField(choices=[('standard', 'Standard'), ('delux', 'Delux'), ('family suite', 'Family Suite'), ('business suite', 'Business Suite')], max_length=20)),
                ('room_status', models.CharField(choices=[('available', 'Available'), ('resersved', 'Resersved'), ('occupied', 'Occupied'), ('not available', 'Not Available'), ('being serviced', 'Being Serviced'), ('other', 'Other')], max_length=30)),
                ('booking_price', models.IntegerField()),
                ('is_smoking', models.BooleanField(default=False)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotel_room.hotel')),
            ],
        ),
    ]
